### ISSUE TITLE
flask-argon2 not support FreeBSD

### ISSUE THREAD

**Issue by kaelianbaudelet** [red-coracle/flask-argon2#11]
Hey, Due to a lack of **FreeBSD** support for dependencies such as **Argon2-cffi-bindings** & **Argon2-cffi** which you use in **flask_argon_2**, impossible to install on FreeBSD, FreeBSD support would be super interesting in a recent update

Afi.

**Comment by red-coracle** [comment]
I've admittedly never used FreeBSD before, but I installed version 13.1 to a virtual machine and then the following commands:

```bash
$ pkg install py38-pip
$ pip install flask_argon2
```

It seems to work fine:
![image](https://user-images.githubusercontent.com/4132735/176558924-ece0045e-aecf-4b39-9d7b-86ce567d0dda.png)

This library is merely a wrapper though and uses plain Python code. Any platform-specific issues would need to be resolved upstream in `argon2-cffi` and/or `argon2-cffi-bindings`.
